/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        battron: {
          black: '#0d0d0d',
          ink: '#161616',
          green: '#a4ce3a',
          greenBright: '#c6f23e',
          greenDark: '#55731a',
          greenDeep: '#16240b',
          page: '#f5f8ee',
          card: '#ffffff',
          line: '#e1ead0',
          muted: '#8a9099',
          slate: '#5b6470',
          red: '#c0392b',
          inputBg: '#fcfdfb',
          readonlyBg: '#eef3e4',
          readonlyText: '#3a4a1b',
          summary: '#15240a',
          btnSText: '#2e3d10',
          chipWarnBg: '#f6d6c9',
          chipWarnText: '#7a2417',
          gradeA: '#a4ce3a',
          gradeB: '#cfe35a',
          gradeC: '#e6b73c',
          gradeD: '#d9603a',
          gradeCText: '#3a2c00',
          flagOkBg: '#eaf4d3',
          flagOkText: '#2e3d10',
          flagWarnBg: '#fdebcf',
          flagWarnText: '#7a4a12',
          flagBadBg: '#f7dad5',
          flagBadText: '#7a2417',
        },
      },
      fontFamily: {
        sans: ['-apple-system', '"Segoe UI"', 'Roboto', 'Arial', 'sans-serif'],
      },
      fontSize: {
        '11': '11px',
        '12': '12px',
        '13': '13px',
        '14': '14px',
        '15': '15px',
        '18': '18px',
        '30': '30px',
        '46': '46px',
      },
      borderRadius: {
        '7': '7px',
        '8': '8px',
        '9': '9px',
        '10': '10px',
        '11': '11px',
        '12': '12px',
        '14': '14px',
        '18': '18px',
        pill: '999px',
      },
      maxWidth: {
        container: '680px',
      },
      boxShadow: {
        header: '0 2px 8px rgba(0,0,0,.25)',
        card: '0 1px 3px rgba(0,0,0,.04)',
        bar: '0 -2px 10px rgba(0,0,0,.08)',
      },
      screens: {
        xs: { max: '380px' },
      },
    },
  },
  plugins: [],
}
